dataset:
  dir: ./datasets
  format: nx
  name: BCDB
  split:
  - 0.8
  - 0.1
  - 0.1
  task: graph
  task_type: classification
  transductive: false
device: cpu
gnn:
  act: prelu
  agg: mean
  batchnorm: true
  dim_inner: 180
  dropout: 0.0
  layer_type: gatconv
  layers_mp: 4
  layers_post_mp: 1
  layers_pre_mp: 1
  normalize_adj: false
  stage_type: stack
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: cross_entropy
  type: gnn
optim:
  base_lr: 0.01
  max_epoch: 100
  optimizer: adam
out_dir: results/BCDB_Dataset_grid_BCDB_grid
train:
  batch_size: 32
  ckpt_period: 100
  eval_period: 20
